### ISSUE TITLE
 micro-gw toolkit executable not recognized on Windows 

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [wso2/WSO2-Training#12]
**Description:**

Downloaded the toolkit, put it in PATH and attempted to init petstore project. 

`micro-gw : The term 'micro-gw' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was   
included, verify that the path is correct and try again.`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

wso2am-micro-gw-toolkit-windows-3.2.0

**OS, DB, other environment details and versions:**    

Windows x86 

**Steps to reproduce:**

Download the cmdlt. Put executable in path. Init a project or even a --help flag.

**Related Issues:**

**Comment by GoodFaithParadigm8** [comment]
Worked through old issue. New issue below.

```
micro-gw init petstore -a https://petstore.swagger.io/v2/swagger.json
Initializing Toolkit...
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.AccessDeniedException: C:\PROGRA~1\WSO2AM~1\WSO2AM~1.0\bin\..\logs\microgw.log.lck
java.nio.file.AccessDeniedException: C:\PROGRA~1\WSO2AM~1\WSO2AM~1.0\bin\..\logs\microgw.log.lck
 at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:478)
        at java.util.logging.FileHandler.<init>(FileHandler.java:281)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.logging.LogManager$5.run(LogManager.java:966)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
        at java.util.logging.LogManager.access$1500(LogManager.java:145)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
        at java.util.logging.Logger.getHandlers(Logger.java:1777)
        at java.util.logging.Logger.log(Logger.java:735)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
        at org.slf4j.impl.JDK14LoggerAdapter.error(JDK14LoggerAdapter.java:559)
        at org.wso2.apimgt.gateway.cli.utils.ToolkitLibExtractionUtils.extractPlatformAndRuntime(ToolkitLibExtractionUtils.java:50)
        at org.wso2.apimgt.gateway.cli.cmd.InitCmd.execute(InitCmd.java:104)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:50)
micro-gw: Internal error occurred while executing command. - Error while unzipping platform while project setup
```

**Comment by GoodFaithParadigm8** [comment]
The problem was that the folder inherited all the properties from a parent folder. It made the logs folder unwrittable. Now after setting all the permissions correctly this is the error that I get.

```
PS C:\Users\xxxx\xxxx\xxxx> micro-gw init petstore -a https://petstore.swagger.io/v2/swagger.json
Initializing Toolkit...
micro-gw: Internal error occurred while executing command. - Error while unzipping platform while project setup
```
